---
- name: Проверка наличия файлов .sql
  hosts: localhost
  become: true
  tasks:
    - name: Поиск файлов .sql
      find:
        paths: /var/backups/database
        patterns: "*.sql"
      register: result
      become: true
 
    - name: Вывод найденных файлов .sql
      debug:
        var: result.files
 
