---
- name: Резервное копирование баз данных
  hosts: localhost
  become: true
  tasks:
    - name: Создание директории для резервных копий
      file:
        path: /var/backups/database
        state: directory
        mode: '0755'
      become: true
 
    - name: Копирование файла скрипта резервного копирования
      copy:
        src: backup_script.sh
        dest: /var/backups/database/backup_script.sh
        mode: '0755'
      become: true
 
    - name: Запуск скрипта резервного копирования
      command: /var/backups/database/backup_script.sh
      become: true
 
    - name: Настройка Cron для резервного копирования
      cron:
        name: Резервное копирование баз данных
        minute: '30'
        hour: '3'
        job: /var/backups/database/backup_script.sh
      become: true
