---
- name: Резервное копирование баз данных
  hosts: node1,node2
  become: true
  tasks:
    - name: Создание директории для резервных копий
      file:
        path: /var/backups/database
        state: directory
        mode: '0755'
      become: true

    - name: Установка необходимых пакетов Python
      apt:
        name: python
        state: present
      become: true

    - name: Копирование файла шаблона резервного копирования
      template:
        src: backup_script_template.sh
        dest: /var/backups/database/backup_script.sh
        mode: '0755'
      become: true

    - name: Загрузка сценария резервного копирования на серверы
      copy:
        src: /var/backups/database/backup_script.sh
        dest: /destination/path/backup_script.sh
      become: true

    - name: Настройка Cron для резервного копирования
      cron:
        name: Резервное копирование баз данных
        minute: '40'
        hour: '13'
        job: /var/backups/database/backup_script.sh
      become: true
