---
- name: Установка пакетов PHP для Zabbix
  hosts: node1, node2
  become: true
 
  tasks:
    - name: Установка пакетов PHP
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - php
        - php-fpm
        - php-mysqli
        - php-pear
        - php-cgi
        - php-common
        - php-ldap
        - php-mbstring
        - php-snmp
        - php-gd
        - php-xml
        - php-bcmath
        - php-json
          
    - name: Set date.timezone in php.ini
      lineinfile:
        path: /etc/php/7.4/fpm/php.ini
        regexp: '^;?date.timezone ='
        line: 'date.timezone = "Europe/Moscow"'

    - name: Set max_execution_time in php.ini
      lineinfile:
        path: /etc/php/7.4/fpm/php.ini
        regexp: '^;?max_execution_time ='
        line: 'max_execution_time = 300'

    - name: Set post_max_size in php.ini
      lineinfile:
        path: /etc/php/7.4/fpm/php.ini
        regexp: '^;?post_max_size ='
        line: 'post_max_size = 16M'

    - name: Set max_input_time in php.ini
      lineinfile:
        path: /etc/php/7.4/fpm/php.ini
        regexp: '^;?max_input_time ='
        line: 'max_input_time = 300'

    - name: Set max_input_vars in php.ini
      lineinfile:
        path: /etc/php/7.4/fpm/php.ini
        regexp: '^;?max_input_vars ='
        line: 'max_input_vars = 10000'


    - name: Enable and start php-fpm
      systemd:
        name: php7.4-fpm
        enabled: yes
        state: started

    - name: Create nginx html directory
      file:
        path: /var/www/html
        state: directory
        mode: '0755'      
        
    - name: Create phpinfo file
      copy:
        content: "<?php phpinfo(); ?>"
        dest: /var/www/html/index.php

    - name: Set permissions in index.php
      file: 
        path: /var/www/html/index.php
        mode: '0644'
