---
- name: Установка необходимых пакетов Python
  hosts: localhost
  become: true
  tasks:
    - name: Установка пакетов Python
      apt:
        name: python
        state: present
      become: true
