---
- name: Развертывание базы данных MySQL с репликацией
  hosts: localhost
  remote_user: "{{ your_login_user }}"
  become: yes
  tasks:
    - name: Обновление списка пакетов
      apt:
        update_cache: yes
      become: yes
 
    - name: Установка пакета MySQL
      apt:
        name: mysql-server
        state: present
      become: yes
 
    - name: Установка пакета pymysql
      apt:
        name: python3-pymysql
        state: present
      become: yes
 
    - name: Запуск и настройка службы MySQL
      service:
        name: mysql
        state: started
        enabled: yes
      become: yes
 
    - name: Обновление пароля root для MySQL
      mysql_user:
        name: "{{ your_login_user }}"
        password: "{{ your_new_pass }}"
        login_unix_socket: /var/run/mysqld/mysqld.sock
        login_password: "{{ your_curent_pass_db }}"
        check_implicit_admin: yes
      become: yes
 
    - name: Удаление неиспользуемых пользователей и баз данных
      mysql_user:
        name: "{{ item }}"
        state: absent
        login_unix_socket: /var/run/mysqld/mysqld.sock
        login_password: "{{ your_curent_pass_db }}"
      with_items:
        - test
      become: yes
 
    - name: Создание базы данных
      mysql_db:
        name: mydb
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock
        login_password: "{{ your_curent_pass_db }}"
      become: yes
 
    - name: Создание пользователя базы данных
      mysql_user:
        name: "{{ user_name_db }}"
        password: "{{ your_pass_db_user }}"
        priv: 'mydb.*:ALL'
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock
        login_password: your_curent_password
      become: yes
 
    - name: Создание пользователей репликации
      mysql_user:
        name: replicator
        password: "{{ your_pass_db_user }}"
        priv: '*.*:REPLICATION SLAVE'
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock
        login_password: "{{ your_curent_pass_db }}"
      become: yes
 
    - name: Настройка подчиненного устройства для репликации
      mysql_replication:
        mode: changeprimary
        master_host: "{{ ip_address_master }}"
        master_user: replicator
        master_password: "{{ your_pass_db_user }}"
        master_log_file: mysql-bin.000001
        master_log_pos: 344
        login_unix_socket: /var/run/mysqld/mysqld.sock
        login_password: "{{ your_curent_pass_db }}"
      become: yes
 
    - name: Запуск репликации
      mysql_replication:
        mode: startreplica
        login_password: "{{ your_curent_pass_db }}"
      become: yes
