- name: Генерация локали и перезапуск Nginx
  hosts: node1, node2
  become: true

  tasks:
    - name: Генерация локали "en_US"
      shell: locale-gen en_US
      changed_when: false

    - name: Переконфигурация локалей
      become: true
      command: dpkg-reconfigure --frontend noninteractive locales
      changed_when: false
      register: reconfigure_result
      failed_when: reconfigure_result.rc != 0 and reconfigure_result.rc != 30  # 30 indicates already configured

    - name: Перезапуск Nginx
      service:
        name: nginx
        state: restarted
